apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: stream
  name: stream
spec:
  serviceName: "stream"
  replicas: 1
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stream
    spec:
      containers:
        # streamer
        - image: prologic/tube
          name: streamer
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /data
        # Torrent
        - image: jpillora/cloud-torrent
          name: torrent
          args: ["--config-path=/config/cloud-torrent.json", "--port=9000"]
          ports:
            - containerPort: 9000
          resources: {}
          env:
            - name: AUTH
              valueFrom:
                secretKeyRef:
                  name: torrent
                  key: auth
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: stream
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi