apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: stream
  name: stream
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: streama
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: torrent
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: stream
  sessionAffinity: None
  type: LoadBalancer
