/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algs;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testSqrt() {
        assertEquals(App.sqrt(4), 2.0);
    }

    @Test public void testAverage() {
        assertEquals(App.testAverage(), 0.0);
    }

    @Test public void testBinarySearch() {
        int[] haystack = { 1, 71, 3, 4, 5, 6, 7 };
        assertEquals(0, App.binarySearch(1, haystack));
        assertEquals(6, App.binarySearch(71, haystack));
    }
}
