version: '3.3'
services:
  test: &test
    image: elixir:alpine
    command: mix test
    working_dir: /usr/local/src
    environment:
      - MIX_ENV=test
    volumes:
      - .:/usr/local/src
  test-listen:
    <<: *test
    command: mix test --listen-on-stdin
