version: '3.7'
services:
  test:
    image: node:alpine
    command: npm test
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules: {}