/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package euler;

public class Library {
    // Find the sum of all the multiples of 3 or 5 below 1000.
    public int one(int r) {
        int acc = 0;
        for (int i = 1; i < r; i++) {
            boolean multTree = i % 3 == 0;
            boolean multFive = i % 5 == 0;
            if (multTree || multFive) {
                acc += i;
            }
        }
        return acc;
    }
    // By considering the terms in the Fibonacci sequence whose values do
    // not exceed four million, find the sum of the even-valued terms.
    public int two(int n) {
        int n1 = 0;
        int n2 = 1;
        int b = 0;
        int res = 0;
        for (; n > 0; n--) {
            b = n1 + n2;
            n1 = n2;
            n2 = b;
            res += b;
            System.out.println("b: " + res);
        }
        return res;
    }
    // two(10)
}
